apiVersion: v1
kind: ConfigMap
metadata:
  name: piday-server-env
  # namespace: piday-staging
data:
  GIN_MODE: release
  NODE_ENV: staging

  RECHARGING_ADDRESS: "GBFF6AGW2TBXKBEGJAKMXPYV3MRTGCIJ74J66YSBOILBMJRRGLSLJWV5"
  KEYCLOAK_CERTS_URL: "https://staging-auth.piday.world/realms/piday/protocol/openid-connect/certs"

  GET_ACCOUNT_PAYMENTS_URL: "https://api.testnet.minepi.com/accounts"
