apiVersion: apps/v1
kind: Deployment
metadata:
  name: piday-server-deployment
  # namespace: staging
spec:
  selector:
    matchLabels:
      app: piday-server-deployment
  replicas: 1
  template:
    spec:
      containers:
        - image: registry.digitalocean.com/davinqi/piday-server:v0.0.2
          imagePullPolicy: Always
          name: piday-server-deployment
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          envFrom:
            - configMapRef:
                name: piday-server-env
