prismaDebug: true

piNetworkPayment:
  # cursor: "54060263728488449"
  cursor: "60067239348408321"
  #        60067239348408321

redis:
  host: localhost
  password:
  port: 6379
  db: 3

keycloak:
  baseUrl: https://piday-dev-auth.dvqdev.com
  realm: "piday"
  clientId: "auth-client"
  clientSecret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

mailgun:
  apiKey: "key-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  domain: mg.piday.world

mailerSend:
  apiKey: "mlsn.18891c260994363fac758a7e34598ceaf869a381361c7ebd877d4eb9487b3f8d"
