prismaDebug: true

redis:
  host: localhost
  password:
  port: 6379
  db: 3

keycloak:
  baseUrl: KEYCLOAK_BASE_URL
  realm: "piday"
  clientId: "auth-client"
  clientSecret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

mailgun:
  apiKey: "key-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  domain: mg.piday.world
