apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: piday-dev

resources:
  - ../../base

labels:
  - includeSelectors: true
    pairs:
      env: dodev

patches:
  - path: deployment.yaml
  # - path: configMap.yaml
