apiVersion: apps/v1
kind: Deployment
metadata:
  name: piday-server-deployment
#  namespace: staging
spec:
  selector:
    matchLabels:
      app: piday-server-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: piday-server-deployment
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - image: registry.digitalocean.com/davinqi/piday-web:v0.0.1
          imagePullPolicy: Always
          name: piday-server-deployment
          #        ports: # Is it useful?
          #        - containerPort: 8080
          #          protocol: TCP
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: piday-server-env
