apiVersion: apps/v1
kind: Deployment
metadata:
  name: piday-server-deployment
#  namespace: staging
spec:
  selector:
    matchLabels:
      app: piday-server-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: piday-server-deployment
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "piday-server"
        vault.hashicorp.com/agent-pre-populate: "false"
        vault.hashicorp.com/agent-inject-secret-config: "kv-piday-server/data/env"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "kv-piday-server/data/env" -}}
            export DATABASE_URL="{{ .Data.data.DATABASE_URL }}"
            export KEYCLOAK_CLIENT_ID="{{ .Data.data.KEYCLOAK_CLIENT_ID }}"
            export KEYCLOAK_CLIENT_SECRET="{{ .Data.data.KEYCLOAK_CLIENT_SECRET }}"
            export TEST="{{ .Data.TEST }}"
          {{- end }}
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: default
      containers:
        - image: registry.digitalocean.com/davinqi/piday-server:v0.0.78
          imagePullPolicy: Always
          command: ["sh", "-c"]
          args: ["source /vault/secrets/config && yarn start:prod"]
          name: piday-server-deployment
          #        ports: # Is it useful?
          #        - containerPort: 8080
          #          protocol: TCP
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: piday-server-env
