---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: piday-server-virtual-service
  namespace: piday-dev
spec:
  hosts:
    - "app-dev.piday.world"
  gateways:
    - istio-gateway
  http:
    - route:
        - destination:
            port:
              number: 80
            host: piday-server-service