---
apiVersion: v1
kind: Service
metadata:
  name: piday-server-service
  namespace: piday-dev
spec:
  selector:
    app: piday-server-deployment
  ports:
    - name: apiv1
      protocol: TCP
      port: 80 # This port for ingress
      targetPort: 3100
    - name: apiv1-https
      protocol: TCP
      port: 443 # This port for ingress
      targetPort: 443
