apiVersion: v1
kind: ConfigMap
metadata:
  name: piday-server-env
#  namespace: staging
data:
  GIN_MODE: release
  NODE_ENV: dev

  RECHARGING_ADDRESS: "GDMCTLK2HSMP3BDPYEUEBR2E53PKPUXS6UAZHIKV4T3WPNJXHCLDVXHM"
  KEYCLOAK_CERTS_URL: "https://auth.piday.world/realms/piday/protocol/openid-connect/certs"

  GET_ACCOUNT_PAYMENTS_URL: "https://api.minepi.com/accounts"

  REDIS_DB: "4"
