apiVersion: v1
kind: ConfigMap
metadata:
  name: piday-server-env
#  namespace: staging
data:
  GIN_MODE: release
  NODE_ENV: prod

  FRONTEND_URL: https://piday.world

  RECHARGING_ADDRESS: "GBFF6AGW2TBXKBEGJAKMXPYV3MRTGCIJ74J66YSBOILBMJRRGLSLJWV5"
  KEYCLOAK_CERTS_URL: "https://auth.piday.world/realms/piday/protocol/openid-connect/certs"

  GET_ACCOUNT_PAYMENTS_URL: "https://api.mainnet.minepi.com/accounts"
  ACCOUNT_PAYMENTS_CURSOR: "54060263728488449"

  REDIS_DB: "4"
