apiVersion: apps/v1
kind: Deployment
metadata:
  name: piday-server-deployment
  # namespace: prod
spec:
  selector:
    matchLabels:
      app: piday-server-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: piday-server-deployment
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "piday-server"
        vault.hashicorp.com/agent-pre-populate: "false"
        vault.hashicorp.com/agent-inject-secret-config: "piday-prod/data/server-env"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "piday-prod/data/server-env" -}}
            export DATABASE_URL="{{ .Data.data.DATABASE_URL }}"
            export KEYCLOAK_BASE_URL="{{ .Data.data.KEYCLOAK_BASE_URL }}"
            export KEYCLOAK_CLIENT_SECRET="{{ .Data.data.KEYCLOAK_CLIENT_SECRET }}"
            export REDIS_HOST="{{ .Data.data.REDIS_HOST }}"
            export REDIS_PASSWORD="{{ .Data.data.REDIS_PASSWORD }}"
            export REDIS_PORT="{{ .Data.data.REDIS_PORT }}"
            export MAILGUN_API_KEY="{{ .Data.data.MAILGUN_API_KEY }}"
          {{- end }}
    spec:
      serviceAccountName: default
      containers:
        - image: registry.digitalocean.com/davinqi/piday-server:v0.0.92
          imagePullPolicy: Always
          name: piday-server-deployment
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          # envFrom:
          #   - configMapRef:
          #       name: piday-server-env
