apiVersion: v1
kind: ConfigMap
metadata:
  name: piday-web-env
  # namespace: piday-prod
data:
  REACT_APP_VERSION: 0.0.1
  BACKEND_BASE_URL: http://piday-server-service.piday-prod

  KEYCLOAK_ISSUER: "https://auth.piday.world/realms/piday"
  END_SESSION_URL: "https://auth.piday.world/realms/piday/protocol/openid-connect/logout"
