apiVersion: apps/v1
kind: Deployment
metadata:
  name: piday-web-deployment
  # namespace: prod
spec:
  selector:
    matchLabels:
      app: piday-web-deployment
  replicas: 2
  template:
    spec:
      containers:
        - image: registry.digitalocean.com/davinqi/piday-web:v0.0.5-prod
          imagePullPolicy: Always
          name: piday-web-deployment
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          envFrom:
            - configMapRef:
                name: piday-web-env
