apiVersion: apps/v1
kind: Deployment
metadata:
  name: piday-web-deployment
  # namespace: piday-prod
spec:
  replicas: 3
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "piday-server"
        vault.hashicorp.com/agent-pre-populate: "false"
        vault.hashicorp.com/agent-inject-secret-config: "piday-prod/data/server-env"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "piday-prod/data/server-env" -}}
            export KEYCLOAK_CLIENT_SECRET="{{ .Data.data.KEYCLOAK_CLIENT_SECRET }}"
          {{- end }}
    spec:
      serviceAccountName: default
      containers:
        - image: registry.digitalocean.com/davinqi/piday-web:v0.0.151
          imagePullPolicy: Always
          name: piday-web-deployment
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          envFrom:
            - configMapRef:
                name: piday-web-env
