apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: piday-prod

resources:
  - ../../base

labels:
  - includeSelectors: true
    pairs:
      env: doprod

patches:
  - path: deployment.yaml
    target:
      namespace: piday-staging
  - path: routing.yaml
    target:
      namespace: piday-staging
