apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: piday-prod

commonLabels:
  env: doprod

bases:
  - ../../base
# patchesStrategicMerge:
#   - configMap.yaml
#   - deployment.yaml
#   - routing.yaml
