---
kind: pipeline
type: kubernetes
name: Piday-Next-Web-Deployment

platform:
  os: linux
  arch: amd64

steps:
  - name: Build
    image: node
    commands:
      - export $(cat piday-web/.env | xargs)
      - echo $VERSION-dev > .tags

  # Make docker image
  - name: Build-Docker-Image-Dev
    image: plugins/docker
    when:
      status:
        - success
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: registry.digitalocean.com/davinqi/piday-web
      registry: registry.digitalocean.com
      # context: piday-web
      dockerfile: piday-web/Dockerfile
      build_args:
        - BUILD_ENV=:dev

  - name: Deploy-Dev
    image: digitalocean/doctl:1-latest
    when:
      status:
        - success
    environment:
      DIGITALOCEAN_ACCESS_TOKEN:
        from_secret: DIGITALOCEAN_ACCESS_TOKEN
        KUBECONFIG: /root/.kube/config
      KUBE_CLUSTER_ID:
        from_secret: KUBE_CLUSTER_ID_DEV
    commands:
      - /app/doctl auth init --access-token $DIGITALOCEAN_ACCESS_TOKEN
      - /app/doctl kubernetes cluster kubeconfig save $KUBE_CLUSTER_ID
      - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - ./kubectl apply -k piday-web/deployment/dok8s/overlays/dodev

  - name: notify-success
    image: drillster/drone-email
    environment:
      DEV_EMAIL_PASSWORD:
        from_secret: DEV_EMAIL_PASSWORD
    settings:
      host: smtp.mailgun.org
      username: dev@mg.darenstar.com
      password:
        from_secret: DEV_EMAIL_PASSWORD
      from: dev@darenstar.com
      recipients:
        - hanggicrown@gmail.com
      subject: "[Piday Web](DEV) Build success!"
      body: |
        Build success!
        Please check the result at: https://

        Link to the website: https://app-dev.piday.world
    when:
      status:
        - success

  - name: notify-failure
    image: drillster/drone-email
    environment:
      DEV_EMAIL_PASSWORD:
        from_secret: DEV_EMAIL_PASSWORD
    settings:
      host: smtp.mailgun.org
      username: dev@mg.darenstar.com
      password:
        from_secret: DEV_EMAIL_PASSWORD
      from: dev@darenstar.com
      recipients:
        - hanggicrown@gmail.com
      subject: "[Piday Web](DEV) Build failed!"
      body: |
        Build failed!
        Please check the result at: https://
    when:
      status:
        - failure

node_selector:
  kubernetes.io/os: linux
  # doks.digitalocean.com/node-pool: amd-pool-4c-8g
  # doks.digitalocean.com/node-pool: regular-pool
  # doks.digitalocean.com/node-pool: intel-pool-4c-8g

trigger:
  branch:
    - main
  event:
    - push
