---
# 单元测试
kind: pipeline
type: kubernetes
name: Piday-Next-Server-Deployment

platform:
  os: linux
  arch: amd64

steps:
  - name: Build
    image: node
    commands:
      - export $(grep -v '^#' piday-server/.env | xargs)
      - echo $VERSION > .tags

  # Make docker image
  - name: Build-Docker-Image
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_USERNAME
      repo: registry.digitalocean.com/davinqi/piday-server
      registry: registry.digitalocean.com
      dockerfile: piday-server/Dockerfile.drone
      build_args_from_env:
        - VERSION
        - TIME

  - name: Deploy-Dev
    image: digitalocean/doctl:1-latest
    when:
      status:
        - success
    environment:
      DIGITALOCEAN_ACCESS_TOKEN:
        from_secret: DIGITALOCEAN_ACCESS_TOKEN
        KUBECONFIG: /root/.kube/config
      KUBE_CLUSTER_ID:
        from_secret: KUBE_CLUSTER_ID_DEV
    commands:
      - /app/doctl auth init --access-token $DIGITALOCEAN_ACCESS_TOKEN
      - /app/doctl kubernetes cluster kubeconfig save $KUBE_CLUSTER_ID
      - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - ./kubectl apply -k piday-server/deployments/dok8s/overlays/dodev

  - name: notify-success
    image: drillster/drone-email
    environment:
      DEV_EMAIL_PASSWORD:
        from_secret: DEV_EMAIL_PASSWORD
    settings:
      host: smtp.mailgun.org
      username: dev@mg.darenstar.com
      password:
        from_secret: DEV_EMAIL_PASSWORD
      from: piday-dev@darenstar.com
      recipients:
        - hanggicrown@gmail.com
      subject: "[Piday Server](DEV) Build success!"
      body: |
        Build success!
        Please check the result at: https://

        Link to the website: https://app-dev.piday.world
    when:
      status:
        - success

  - name: notify-failure
    image: drillster/drone-email
    environment:
      DEV_EMAIL_PASSWORD:
        from_secret: DEV_EMAIL_PASSWORD
    settings:
      host: smtp.mailgun.org
      username: dev@mg.darenstar.com
      password:
        from_secret: DEV_EMAIL_PASSWORD
      from: piday-dev@darenstar.com
      recipients:
        - hanggicrown@gmail.com
      subject: "[Piday Server](DEV) Build failed!"
      body: |
        Build failed!
        Please check the result at: https://
    when:
      status:
        - failure

node_selector:
  kubernetes.io/os: linux

trigger:
  branch:
    - main
  event:
    - push
