FROM node:20 AS builder
WORKDIR /app
COPY ./piday-server/package.json ./
RUN corepack enable
RUN yarn
RUN npm rebuild bcrypt --build-from-source
COPY ./piday-server .
ENV TZ Asia/Shanghai
# ENV NODE_ENV production
RUN npx prisma generate
RUN yarn build

FROM node:20-slim
WORKDIR /app
RUN corepack enable
# ENV NODE_ENV production
ENV TZ Asia/Shanghai
COPY --from=builder /app ./
CMD ["yarn", "start:prod"]
