apiVersion: apps/v1
kind: Deployment
metadata:
  name: piday-web-deployment
  # namespace: piday-dev
spec:
  replicas: 2
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "piday-server"
        vault.hashicorp.com/agent-pre-populate: "false"
        vault.hashicorp.com/agent-inject-secret-config: "kv-piday-server/data/env"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "kv-piday-server/data/env" -}}
            export DATABASE_URL="{{ .Data.DATABASE_URL }}"
            export TEST="{{ .Data.TEST }}"
          {{- end }}
    spec:
      serviceAccountName: default
      containers:
        - image: registry.digitalocean.com/davinqi/piday-web:v0.0.38
          imagePullPolicy: Always
          name: piday-web-deployment
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          envFrom:
            - configMapRef:
                name: piday-web-env
