apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: piday-dev

commonLabels:
  env: dodev

bases:
  - ../../base
# patchesStrategicMerge:
#   - configMap.yaml
#   - deployment.yaml
#   - routing.yaml
