apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: piday-web-virtual-service
  # namespace: piday-dev
spec:
  hosts:
    - "app-dev.piday.world"
  gateways:
    - dev/istio-gateway
  http:
    - route:
        - destination:
            port:
              number: 80
            host: piday-web-service
